search by numeric
funky-monkey/IsoCountryCodes pull request #8
Opened 2018-02-21 11:18 UTC by kassemitani

Added ability to search by numeric as i need it in my case

2018-02-21 20:59 UTC, funky-monkey commented on IsoCountryCodes.swift
> +        var country = IsoCountries.allCountries.filter( { $0.numeric == numeric } )
Can you make this a `let`? It is never mutated.

2018-02-21 21:00 UTC, funky-monkey requested changes
For the rest it looks good, just a small comment

2018-02-21 21:00 UTC, funky-monkey commented on IsoCountryCodes.swift
> +        var country = IsoCountries.allCountries.filter( { $0.numeric == numeric } )
If this is changes i'll merge it :)

2018-02-22 07:07 UTC, kassemitani commented on IsoCountryCodes.swift
> +        var country = IsoCountries.allCountries.filter( { $0.numeric == numeric } )
done

2018-02-22 22:12 UTC, merged